env: URL=https://www.dropbox.com/sh/hz03qag74f3p6ol/AAAFJEDRdwMMP_1pTK4kpSOya/rust-2015-05-13-b32debb-x86_64-unknown-linux-gnu-c3236b585d1c85649ebd35892bcb67b124936758.tar.gz

install:
  - source install.sh

script:
  - ./test.sh

branches:
  only: master

notifications:
  email:
    on_success: never
