env: URL=https://www.dropbox.com/sh/hz03qag74f3p6ol/AADmDjm4LJWOXKqwP1VL1-6ea/rust-2015-05-27-8b84965-x86_64-unknown-linux-gnu-21a963b3753eb550f91d419724e31224de775020.tar.gz

addons:
  apt:
    packages:
      - valgrind

install:
  - source install.sh

script:
  - ./test.sh

branches:
  only: master

notifications:
  email:
    on_success: never
