env: URL=https://www.dropbox.com/sh/hz03qag74f3p6ol/AADOLQA-i0W6P-6M6Lt345aMa/rust-2015-07-01-9d270f0-x86_64-unknown-linux-gnu-c183fa37e1c48386841d84c5460b59e3afd85f49.tar.gz

addons:
  apt:
    packages:
      - valgrind

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update

install:
  - sudo apt-get install libstdc++6
  - source install.sh

script:
  - ./test.sh

branches:
  only: master

notifications:
  email:
    on_success: never
