env: URL=https://www.dropbox.com/sh/hz03qag74f3p6ol/AABGxiO934a6y9ZCULI0zBwXa/rust-2015-06-18-a9eda99-x86_64-unknown-linux-gnu-88034602459af55b250836da861a133815222fa8.tar.gz

addons:
  apt:
    packages:
      - valgrind

install:
  - source install.sh

script:
  - ./test.sh

branches:
  only: master

notifications:
  email:
    on_success: never
